### ISSUE TITLE
Text Manager

### ISSUE THREAD

**Issue by WaterKH** [JJEInc/SteamBit#10]
Variables:
- [x] Create a wrapper for X amount of Text UI Elements

Methods:
- [ ] Add ability to animate text (Movement, color, size)
- [x] Add display capabilities (Wrap to next line, correct distance placement - *!!*Probably could use canvas grouping layouts for this actually*!!*)

**Comment by Bio-Roxas** [comment]
- [ ] Add text for townspeople that all overlays over each other.
      *Essentially want this to mimic what hearing a crowd of people would sound like. Hard to make out anything.

**Comment by WaterKH** [comment]
- [ ] Make a character limit for each screen resolution (Seems like the only way to make a viable limit per size)

**Comment by WaterKH** [comment]
This will have to be re-opened later. As of now, a working fix is in place.
