### ISSUE TITLE
Scene 1: Act 1

### ISSUE THREAD

**Issue by Bio-Roxas** [JJEInc/SteamBit#7]
How is the character? (What needs to be more detailed in his demeanor/personality?)
Is it interesting? (If it bores you while reading it, we need to change it.)
How is the development?

- [x] Jacob
- [ ] Ethan

**Comment by WaterKH** [comment]
Critique:
Negatives:
- Do not have Tutorial. I think we should have gameplay based teaching as opposed to text based teaching. 
- If we are going to be having a text based scene system, I think some of the words can be changed like "the thing" - Sounds a little underwhelming to me.
- I think the initialization of the story is a little confusing/ needs a better foundation. It doesn't seem rather interesting that he got lost one day.

Neutrals:
- Darkair is a slur for them correct? We need to find a proper name for them.
- What is our theme? Hope?
- I think a Bio needs to be made of all of the main characters we are going to have.

Positives:
- I like the interaction of the characters, really think that was depicted well.
- I enjoyed the atmosphere and tension you created within the city. Really brought out a pretty interesting dynamic early on between the Darkair's kind and the normal people.
- I like the name Buster for the dog, think we should stick with that.
- The fast paced beginning and conflict I think will draw a lot of people in, really well done I think.
- Overall, I like the progression of the story. It presents a lot of different questions and mystery. For instance, who is this being we have just encountered; how can he see us, but not the others; how are we going to get home now that we've been caught; how are we going to get our dog back.

**Comment by Bio-Roxas** [comment]
Ok I will work on the

**Comment by Bio-Roxas** [comment]
Oops...

**Comment by Bio-Roxas** [comment]
[] add text for townspeople that all overlays over each other.
